include("${CMAKE_CURRENT_LIST_DIR}/windows_runtime_policy.cmake")
set(cases 0)
foreach(root "C:/Windows" "c:\\WINDOWS\\" "D:/Win.dows")
    lezac_windows_runtime_policy(normalized pattern "${root}")
    foreach(suffix "System32/kernel32.dll" "System32\\kernel32.dll" "syswow64/user32.dll")
        set(path "${normalized}/${suffix}")
        foreach(style forward back mixed)
            if(style STREQUAL back)
                string(REPLACE "/" "\\" path "${path}")
            elseif(style STREQUAL mixed)
                string(TOUPPER "${path}" path)
            endif()
            if(NOT path MATCHES "${pattern}")
                message(FATAL_ERROR "system DLL was not excluded: ${path} pattern=${pattern}")
            endif()
            math(EXPR cases "${cases} + 1")
        endforeach()
    endforeach()
    foreach(path "${normalized}Old/System32/kernel32.dll" "E:/app/System32/kernel32.dll" "E:/mingw64/bin/SDL2.dll")
        if(path MATCHES "${pattern}")
            message(FATAL_ERROR "non-system DLL was excluded: ${path} pattern=${pattern}")
        endif()
        math(EXPR cases "${cases} + 1")
    endforeach()
endforeach()
message("windows_runtime_policy=ok cases=${cases} separators=2 case_insensitive=1 exact_root=1")
