function(lezac_windows_runtime_policy root_output regex_output root)
    if(root STREQUAL "")
        message(FATAL_ERROR "Windows system root must not be empty")
    endif()
    # This is one Windows path, not a host-dependent PATH list.
    string(REPLACE "\\" "/" system_root "${root}")
    string(TOLOWER "${system_root}" system_root)
    string(REGEX REPLACE "/+$" "" system_root "${system_root}")
    string(LENGTH "${system_root}" root_length)
    math(EXPR root_last "${root_length} - 1")
    set(system_regex "^")
    foreach(index RANGE ${root_last})
        string(SUBSTRING "${system_root}" ${index} 1 character)
        if(character MATCHES "[a-z]")
            string(TOUPPER "${character}" upper)
            string(APPEND system_regex "[${character}${upper}]")
        elseif(character STREQUAL "/")
            string(APPEND system_regex "[/\\\\]")
        elseif(character MATCHES "[0-9: _-]")
            string(APPEND system_regex "${character}")
        else()
            string(APPEND system_regex "\\${character}")
        endif()
    endforeach()
    string(APPEND system_regex "[/\\\\]")
    set(${root_output} "${system_root}" PARENT_SCOPE)
    set(${regex_output} "${system_regex}" PARENT_SCOPE)
endfunction()
